FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /src

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore ContosoPizza/ContosoPizza.csproj
# Build and publish a release
RUN dotnet publish ContosoPizza/ContosoPizza.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /src
COPY --from=build-env /src/out .
ENTRYPOINT ["dotnet", "ContosoPizza.dll","--environment=Development"]